___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (или Numpy) - это библиотека линейной алгебры для Python; причина, по которой она представляет важность для Data Science с Python состоит в том, что почти все библиотеки в  PyData Ecosystem полагаются на NumPy в качестве одного из своих основных строительных блоков.

Numpy также невероятно быстр, поскольку имеет привязки к библиотекам C. Для получения дополнительной информации о том, почему вы хотели бы использовать массивы (Arrays) вместо списков, ознакомьтесь с этим замечательным [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Мы изучим только основные понятиям NumPy, и для начала нам нужно его установить!

## Инструкция по установке

**Настоятельно рекомендуется установить Python с использованием дистрибутива Anaconda, чтобы обеспечить синхронизацию всех базовых зависимостей (таких как библиотеки линейной алгебры) с использованием установки conda. Если у вас есть Anaconda, установите NumPy, напечатав в терминале или командной строке:**
    
    conda install numpy
    
**Если у вас нет Anaconda и вы не можете ее установить, пожалуйста, обратитесь к официальной документации NumPy по различным инструкциям установки [NumPy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Использование NumPy

После того, как вы установили NumPy, вы можете импортировать его в качестве библиотеки:

In [1]:
import numpy as np

Numpy имеет множество встроенных функций и возможностей. Мы не будем охватывать их все, но вместо этого сосредоточимся на нескольких наиболее важных аспектах NumPy: векторах, массивах, матрицах и генерации чисел. Давайте начнем с обсуждения массивов.

# Массивы Numpy

Массивы NumPy - будет основным способом использования Numpy на протяжении всего курса. Массивы NumPy в основном бывают двух видов: векторы и матрицы. Векторы строго являются массивами 1-d , а матрицы-2-d (но заметьте, что матрица может иметь только одну строку или один столбец).

Давайте начнем наше предисловие с изучения того, как создавать массивы NumPy.

## Создание массивов NumPy

### Из списка Python

Мы можем создать массив с помощью прямого преобразования списка или списка списков:

In [19]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [16]:
np.array(my_list)

array([1, 2, 3])

In [20]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Встроенные методы

Существует множество встроенных способов генерации массивов.

### arange

Верните равномерную дисперсию значений в пределах заданного интервала.

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### нули и единицы

Сгенерируйте массивы нулей или единиц

In [24]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [26]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [27]:
np.ones(3)

array([ 1.,  1.,  1.])

In [28]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Верните равномерно распределённые числа в пределах заданного интервала.

In [29]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [31]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Создает единичную матрицу 

In [37]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

У NumPy также есть много способов создания массивов случайных чисел:

### rand
Создайте массив заданной формы и заполните его случайными образцами 
из равномерной дисперсии по ``[0, 1)``.

In [47]:
np.random.rand(2)

array([ 0.11570539,  0.35279769])

In [46]:
np.random.rand(5,5)

array([[ 0.66660768,  0.87589888,  0.12421056,  0.65074126,  0.60260888],
       [ 0.70027668,  0.85572434,  0.8464595 ,  0.2735416 ,  0.10955384],
       [ 0.0670566 ,  0.83267738,  0.9082729 ,  0.58249129,  0.12305748],
       [ 0.27948423,  0.66422017,  0.95639833,  0.34238788,  0.9578872 ],
       [ 0.72155386,  0.3035422 ,  0.85249683,  0.30414307,  0.79718816]])

### randn

Верните образец (или образцы) из "стандартной нормальной" дисперсии. В отличие от равной дисперсии rand.

In [48]:
np.random.randn(2)

array([-0.27954018,  0.90078368])

In [45]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### randint
Верните случайные целые числа от " low "(включительно) до "high" (эксклюзив).

In [50]:
np.random.randint(1,100)

44

In [51]:
np.random.randint(1,100,10)

array([13, 64, 27, 63, 46, 68, 92, 10, 58, 24])

## Атрибуты и методы массива

Давайте рассмотрим некоторые полезные свойства и методы массива:

In [55]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

## Reshape
Возвращает массив, содержащий те же данные с новой формой.

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Вот полезные методы для нахождения максимальных или минимальных значений. Или для нахождения их индексных местоположений, используя argmin или argmax

In [64]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [61]:
ranarr.max()

49

In [62]:
ranarr.argmax()

4

In [63]:
ranarr.min()

2

In [60]:
ranarr.argmin()

5

## Shape

Shape - это атрибут массивов (не метод):

In [65]:
# Вектор
arr.shape

(25,)

In [66]:
# Обратите внимание на два набора скобок
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
arr.reshape(1,25).shape

(1, 25)

In [70]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Также, вы можете извлечь тип данных объекта из массива:

In [75]:
arr.dtype

dtype('int64')

# Отлично поработали!