___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# Индексация и селекция NumPy 

В этой лекции мы обсудим, как производить выбор элементов или групп элементов из массива.

In [2]:
import numpy as np

In [3]:
#Cоздать образец массива 
arr = np.arange(0,11)

In [4]:
#Показать
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Индексация и выбор скобок
Самый простой способ выбрать один или несколько элементов массива очень напоминает списки Python:

In [5]:
#Получить значение по индексу
arr[8]

8

In [6]:
#Получить значения в диапазоне
arr[1:5]

array([1, 2, 3, 4])

In [7]:
#Получить значения в диапазоне
arr[0:5]

array([0, 1, 2, 3, 4])

## Вещание 

Массивы Numpy отличаются от обычного списка Python из-за их способности к вещанию:

In [8]:
#Установка значения с диапазоном индекса (Вещание)
arr[0:5]=100

#Показать
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
# Сбросить массив, мы скоро увидим, почему было необходимо это сделать
arr = np.arange(0,11)

#Показать
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#Важные заметки о срезах
slice_of_arr = arr[0:6]

#Показать срез
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
# Изменить срез
slice_of_arr[:]=99

#Снова показать срез
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Обратите внимание, что изменения также происходят в нашем исходном массиве!

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Данные не скопированы, это вид исходного массива! Это позволяет избежать проблем с памятью!

In [13]:
#Чтобы получить копию, необходимо прописать детали
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Индексация двумерного (2D) массива (матриц)

Общий формат: **arr_2d[row][col]** или **arr_2d[row,col]**. Для ясности я обычно рекомендую использовать запятую.

In [14]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Показать
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
#Индексация ряда
arr_2d[1]


array([20, 25, 30])

In [16]:
# Формат arr_2d[row][col] или arr_2d[row,col]

# Получение значения отдельного элемента
arr_2d[1][0]

20

In [17]:
# Получение значения отдельного элемента
arr_2d[1,0]

20

In [18]:
# Срез двумерного массива

#Сформировать (2,2) из правого верхнего угла
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [19]:
#Сформировать нижнюю строку
arr_2d[2]

array([35, 40, 45])

In [20]:
##Сформировать нижнюю строку
arr_2d[2,:]

array([35, 40, 45])

### Необычное индексирование

Необычное индексирование позволяет вам выбирать целые ряды или столбцы не по порядку; чтобы показать это, давайте быстро создадим numpy массив:

In [21]:
#Настройка матрицы
arr2d = np.zeros((10,10))

In [22]:
#Длина массива
arr_length = arr2d.shape[1]

In [23]:
#Настройка массива

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

Необычное индексирование позволяет следующее

In [24]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [25]:
#Позволяет в любом порядке
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

## Дополнительная помощь по индексации
Поначалу индексирование двухмерной (2D) матрицы может показаться сложным, особенно когда туда добавлен шаговый размер. Попробуйте поискать изображения в Google, используя NumPy для поиска полезных изображений, например:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Селекция

Давайте кратко рассмотрим, как использовать скобки для выбора на основе операторов сравнения.

In [28]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [31]:
bool_arr = arr>4

In [32]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Отличная работа!